//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormandyNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NormandyNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alertIcon_cancel {
            get {
                object obj = ResourceManager.GetObject("alertIcon_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alertIcon_error {
            get {
                object obj = ResourceManager.GetObject("alertIcon_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alertIcon_info {
            get {
                object obj = ResourceManager.GetObject("alertIcon_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alertIcon_success {
            get {
                object obj = ResourceManager.GetObject("alertIcon_success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alertIcon_warning {
            get {
                object obj = ResourceManager.GetObject("alertIcon_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigLogo {
            get {
                object obj = ResourceManager.GetObject("BigLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bones_eft {
            get {
                object obj = ResourceManager.GetObject("bones_eft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_BoxOff {
            get {
                object obj = ResourceManager.GetObject("icon_BoxOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_BoxOff_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_BoxOff_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_BoxOn {
            get {
                object obj = ResourceManager.GetObject("icon_BoxOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_BoxOn_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_BoxOn_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_CenterOff {
            get {
                object obj = ResourceManager.GetObject("icon_CenterOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_CenterOff_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_CenterOff_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_CenterOn {
            get {
                object obj = ResourceManager.GetObject("icon_CenterOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_CenterOn_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_CenterOn_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Collapse {
            get {
                object obj = ResourceManager.GetObject("icon_Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Collapse_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Collapse_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Download {
            get {
                object obj = ResourceManager.GetObject("icon_Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Download_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Download_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Expand {
            get {
                object obj = ResourceManager.GetObject("icon_Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Expand_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Expand_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Light {
            get {
                object obj = ResourceManager.GetObject("icon_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Light_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Light_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Minus {
            get {
                object obj = ResourceManager.GetObject("icon_Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Minus_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Minus_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Overlay {
            get {
                object obj = ResourceManager.GetObject("icon_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_OverlayDark {
            get {
                object obj = ResourceManager.GetObject("icon_OverlayDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Play {
            get {
                object obj = ResourceManager.GetObject("icon_Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Play_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Play_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_PlayFilled {
            get {
                object obj = ResourceManager.GetObject("icon_PlayFilled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_PlayFilled_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_PlayFilled_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Plus {
            get {
                object obj = ResourceManager.GetObject("icon_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Plus_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Plus_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Refresh {
            get {
                object obj = ResourceManager.GetObject("icon_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_RefreshDark {
            get {
                object obj = ResourceManager.GetObject("icon_RefreshDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_SettingsHide {
            get {
                object obj = ResourceManager.GetObject("icon_SettingsHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_SettingsHide_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_SettingsHide_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_SettingsShow {
            get {
                object obj = ResourceManager.GetObject("icon_SettingsShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_SettingsShow_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_SettingsShow_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Stop {
            get {
                object obj = ResourceManager.GetObject("icon_Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_Stop_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_Stop_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_TextOff {
            get {
                object obj = ResourceManager.GetObject("icon_TextOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_TextOff_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_TextOff_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_TextOn {
            get {
                object obj = ResourceManager.GetObject("icon_TextOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_TextOn_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_TextOn_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_UI_Hide {
            get {
                object obj = ResourceManager.GetObject("icon_UI_Hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_UI_Hide_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_UI_Hide_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_UI_Show {
            get {
                object obj = ResourceManager.GetObject("icon_UI_Show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_UI_Show_Dark {
            get {
                object obj = ResourceManager.GetObject("icon_UI_Show_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_WarningSign {
            get {
                object obj = ResourceManager.GetObject("icon_WarningSign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_WarningSignDark {
            get {
                object obj = ResourceManager.GetObject("icon_WarningSignDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriendlyName,TypeName,EntityType,Category,Notes,ConfigName,CleanName,ModelName
        ///Bull,Animal_BosTaurus_Brown,Animal,N/A,,dayzanimal,Bull,
        ///Cow,Animal_BosTaurusF_Brown,Animal,N/A,,dayzanimal,Cow,
        ///Cow,Animal_BosTaurusF_Spotted,Animal,N/A,,dayzanimal,Cow,
        ///Cow,Animal_BosTaurusF_White,Animal,N/A,,dayzanimal,Cow,
        ///Wolf,Animal_CanisLupus_Grey,Animal,N/A,,dayzanimal,Wolf,
        ///Wolf,Animal_CanisLupus_White,Animal,N/A,,dayzanimal,Wolf,
        ///Buck,Animal_CapraHircus_White,Animal,N/A,,dayzanimal,Buck,
        ///Doe,Animal_CapraHircusF, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lootItems_DAYZ {
            get {
                return ResourceManager.GetString("lootItems_DAYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,FriendlyName,ShortName,Category,Priority,ForceShow,ArmorClass
        ///_54009119af1c881c07000029,Item,Item,Parent Element,-1 Blacklist,FALSE,-1
        ///_5422acb9af1c889c16000029,Weapon,Weapon,Parent Element,-1 Blacklist,FALSE,-1
        ///_543be5664bdc2dd4348b4569,Meds,Meds,Parent Element,0 None,FALSE,-1
        ///_543be5cb4bdc2deb348b4568,Ammo container,Ammo container,Parent Element,-1 Blacklist,FALSE,-1
        ///_543be5dd4bdc2deb348b4569,Money,Money,Parent Element,-1 Blacklist,FALSE,-1
        ///_543be5e94bdc2df1348b4568,Key,Key,Parent Element,-1 Blac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lootItems_EFT {
            get {
                return ResourceManager.GetString("lootItems_EFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriendlyName,EntityType,Category,ObjectName
        ///_base_car,Loot,Vehicle Parts,assets/content/vehicles/modularcar/_base_car_chassis.entity.prefab
        ///12 Gauge Buckshot,Loot,Ammo,ammo.shotgun (world)
        ///12 Gauge Incendiary Shell,Loot,Ammo,ammo.shotgun.fire (world)
        ///12 Gauge Slug,Loot,Ammo,ammo.shotgun.slug (world)
        ///16x Zoom Scope,Loot,Weapons,weapon.mod.8x.scope (world)
        ///1module_cockpit,Loot,Vehicle Parts,assets/content/vehicles/modularcar/module_entities/1module_cockpit.prefab
        ///1module_cockpit_armored,Loot,Vehicle Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lootItems_RUST {
            get {
                return ResourceManager.GetString("lootItems_RUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Nautilus {
            get {
                object obj = ResourceManager.GetObject("Nautilus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
